name: Test Sequence

on:
  push :
  workflow_dispatch :
    inputs:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: ChangeTimeZone
      run: sudo timedatectl set-timezone Asia/Tokyo

    - name: Run
      run: > 
        dotnet run --
        --twitter-api-key "${{ secrets.TWITTER_API_KEY }}"
        --twitter-api-secret "${{ secrets.TWITTER_API_SECRET }}"
        --bearer-token "${{ secrets.BEARER_TOKEN }}"
        --access-token "${{ secrets.ACCESS_TOKEN }}"
        --access-token-secret "${{ secrets.ACCESS_TOKEN_SECRET }}"
        --google-service-account-jwt "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JWT }}"
        --command "TestSequence"
        --actionDate "null"
        --eventDate "2100/1/1"
        --general "test"

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: test_output
        path: ./output
